apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: webapp-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-ms
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp-ms
        tier: frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - webapp-ms
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: beckblurry/php-apache
        name: webapp-ms
        ports:
        - containerPort: 80
        - containerPort: 443
